//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 02:00:16 PM MDT 
//


package jaxb.beerxml2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Fermentable Record Type
 * 
 * <p>Java class for FermentableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * <complexType name="FermentableType">
 *   <complexContent>
 *     <extension base="{urn:beerxml:fermentable:v2}FermentableBase">
 *       <sequence>
 *         <element name="notes" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="max_in_batch" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *         <element name="ibu_gal_per_lb" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="potential" type="{urn:beerxml:unit:v2}DensityType" minOccurs="0"/>
 *         <element name="inventory" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="amount" type="{urn:beerxml:unit:v2}VolumeType"/>
 *                   <element name="amount_as_weight" type="{urn:beerxml:unit:v2}MassType"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FermentableType", namespace = "urn:beerxml:fermentable:v2", propOrder = {
    "notes",
    "maxInBatch",
    "ibuGalPerLb",
    "potential",
    "inventory"
})
public class FermentableType
    extends FermentableBase
{

    protected String notes;
    @XmlElement(name = "max_in_batch")
    protected BigDecimal maxInBatch;
    @XmlElement(name = "ibu_gal_per_lb")
    protected BigDecimal ibuGalPerLb;
    protected DensityType potential;
    protected FermentableType.Inventory inventory;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the maxInBatch property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxInBatch() {
        return maxInBatch;
    }

    /**
     * Sets the value of the maxInBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxInBatch(BigDecimal value) {
        this.maxInBatch = value;
    }

    /**
     * Gets the value of the ibuGalPerLb property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIbuGalPerLb() {
        return ibuGalPerLb;
    }

    /**
     * Sets the value of the ibuGalPerLb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIbuGalPerLb(BigDecimal value) {
        this.ibuGalPerLb = value;
    }

    /**
     * Gets the value of the potential property.
     * 
     * @return
     *     possible object is
     *     {@link DensityType }
     *     
     */
    public DensityType getPotential() {
        return potential;
    }

    /**
     * Sets the value of the potential property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityType }
     *     
     */
    public void setPotential(DensityType value) {
        this.potential = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * @return
     *     possible object is
     *     {@link FermentableType.Inventory }
     *     
     */
    public FermentableType.Inventory getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FermentableType.Inventory }
     *     
     */
    public void setInventory(FermentableType.Inventory value) {
        this.inventory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="amount" type="{urn:beerxml:unit:v2}VolumeType"/>
     *         <element name="amount_as_weight" type="{urn:beerxml:unit:v2}MassType"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amount",
        "amountAsWeight"
    })
    public static class Inventory {

        @XmlElement(namespace = "urn:beerxml:fermentable:v2")
        protected VolumeType amount;
        @XmlElement(name = "amount_as_weight", namespace = "urn:beerxml:fermentable:v2")
        protected MassType amountAsWeight;

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link VolumeType }
         *     
         */
        public VolumeType getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link VolumeType }
         *     
         */
        public void setAmount(VolumeType value) {
            this.amount = value;
        }

        /**
         * Gets the value of the amountAsWeight property.
         * 
         * @return
         *     possible object is
         *     {@link MassType }
         *     
         */
        public MassType getAmountAsWeight() {
            return amountAsWeight;
        }

        /**
         * Sets the value of the amountAsWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link MassType }
         *     
         */
        public void setAmountAsWeight(MassType value) {
            this.amountAsWeight = value;
        }

    }

}
