//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 02:00:16 PM MDT 
//


package jaxb.beerxml2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Addition of Fermentable Type to recipe
 * 
 * <p>Java class for FermentableAdditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * <complexType name="FermentableAdditionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="addition" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{urn:beerxml:fermentable:v2}FermentableBase">
 *                 <sequence>
 *                   <element name="amount" type="{urn:beerxml:unit:v2}MassType"/>
 *                   <element name="add_after_boil" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FermentableAdditionType", namespace = "urn:beerxml:fermentable:v2", propOrder = {
    "addition"
})
public class FermentableAdditionType {

    @XmlElement(required = true)
    protected List<FermentableAdditionType.Addition> addition;

    /**
     * Gets the value of the addition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FermentableAdditionType.Addition }
     * 
     * 
     */
    public List<FermentableAdditionType.Addition> getAddition() {
        if (addition == null) {
            addition = new ArrayList<FermentableAdditionType.Addition>();
        }
        return this.addition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * <complexType>
     *   <complexContent>
     *     <extension base="{urn:beerxml:fermentable:v2}FermentableBase">
     *       <sequence>
     *         <element name="amount" type="{urn:beerxml:unit:v2}MassType"/>
     *         <element name="add_after_boil" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amount",
        "addAfterBoil"
    })
    public static class Addition
        extends FermentableBase
    {

        @XmlElement(namespace = "urn:beerxml:fermentable:v2", required = true)
        protected MassType amount;
        @XmlElement(name = "add_after_boil", namespace = "urn:beerxml:fermentable:v2")
        protected Boolean addAfterBoil;

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link MassType }
         *     
         */
        public MassType getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link MassType }
         *     
         */
        public void setAmount(MassType value) {
            this.amount = value;
        }

        /**
         * Gets the value of the addAfterBoil property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAddAfterBoil() {
            return addAfterBoil;
        }

        /**
         * Sets the value of the addAfterBoil property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAddAfterBoil(Boolean value) {
            this.addAfterBoil = value;
        }

    }

}
