//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 02:00:16 PM MDT 
//


package jaxb.beerxml2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Addition of hops to recipe
 * 
 * <p>Java class for HopAdditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * <complexType name="HopAdditionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="addition" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{urn:beerxml:hop:v2}HopVarietyBase">
 *                 <sequence>
 *                   <element name="form">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <enumeration value="leaf"/>
 *                         <enumeration value="pellet"/>
 *                         <enumeration value="plug"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="use">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <enumeration value="boil"/>
 *                         <enumeration value="dry hop"/>
 *                         <enumeration value="first wort"/>
 *                         <enumeration value="hopback"/>
 *                         <enumeration value="mash"/>
 *                         <enumeration value="continuous boil addition"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="amount" type="{urn:beerxml:unit:v2}MassType"/>
 *                   <element name="time" type="{urn:beerxml:unit:v2}TimeType"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HopAdditionType", namespace = "urn:beerxml:hop:v2", propOrder = {
    "addition"
})
public class HopAdditionType {

    @XmlElement(required = true)
    protected List<HopAdditionType.Addition> addition;

    /**
     * Gets the value of the addition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HopAdditionType.Addition }
     * 
     * 
     */
    public List<HopAdditionType.Addition> getAddition() {
        if (addition == null) {
            addition = new ArrayList<HopAdditionType.Addition>();
        }
        return this.addition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * <complexType>
     *   <complexContent>
     *     <extension base="{urn:beerxml:hop:v2}HopVarietyBase">
     *       <sequence>
     *         <element name="form">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <enumeration value="leaf"/>
     *               <enumeration value="pellet"/>
     *               <enumeration value="plug"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="use">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <enumeration value="boil"/>
     *               <enumeration value="dry hop"/>
     *               <enumeration value="first wort"/>
     *               <enumeration value="hopback"/>
     *               <enumeration value="mash"/>
     *               <enumeration value="continuous boil addition"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="amount" type="{urn:beerxml:unit:v2}MassType"/>
     *         <element name="time" type="{urn:beerxml:unit:v2}TimeType"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "form",
        "use",
        "amount",
        "time"
    })
    public static class Addition
        extends HopVarietyBase
    {

        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected String form;
        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected String use;
        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected MassType amount;
        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected TimeType time;

        /**
         * Gets the value of the form property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForm() {
            return form;
        }

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForm(String value) {
            this.form = value;
        }

        /**
         * Gets the value of the use property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUse() {
            return use;
        }

        /**
         * Sets the value of the use property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUse(String value) {
            this.use = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link MassType }
         *     
         */
        public MassType getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link MassType }
         *     
         */
        public void setAmount(MassType value) {
            this.amount = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link TimeType }
         *     
         */
        public TimeType getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link TimeType }
         *     
         */
        public void setTime(TimeType value) {
            this.time = value;
        }

    }

}
