//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 02:00:16 PM MDT 
//


package jaxb.beerxml2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.beerxml2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.beerxml2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link YeastAdditionType.Addition }
     * 
     */
    public YeastAdditionType.Addition createYeastAdditionTypeAddition() {
        return new YeastAdditionType.Addition();
    }

    /**
     * Create an instance of {@link BeerXml.Cultures }
     * 
     */
    public BeerXml.Cultures createBeerXmlCultures() {
        return new BeerXml.Cultures();
    }

    /**
     * Create an instance of {@link BeerXml.Fermentables }
     * 
     */
    public BeerXml.Fermentables createBeerXmlFermentables() {
        return new BeerXml.Fermentables();
    }

    /**
     * Create an instance of {@link GrainType.YieldDryBasis }
     * 
     */
    public GrainType.YieldDryBasis createGrainTypeYieldDryBasis() {
        return new GrainType.YieldDryBasis();
    }

    /**
     * Create an instance of {@link HopAdditionType.Addition }
     * 
     */
    public HopAdditionType.Addition createHopAdditionTypeAddition() {
        return new HopAdditionType.Addition();
    }

    /**
     * Create an instance of {@link FermentableType }
     * 
     */
    public FermentableType createFermentableType() {
        return new FermentableType();
    }

    /**
     * Create an instance of {@link FermentableType.Inventory }
     * 
     */
    public FermentableType.Inventory createFermentableTypeInventory() {
        return new FermentableType.Inventory();
    }

    /**
     * Create an instance of {@link BeerXml }
     * 
     */
    public BeerXml createBeerXml() {
        return new BeerXml();
    }

    /**
     * Create an instance of {@link MiscellaneousType.Inventory }
     * 
     */
    public MiscellaneousType.Inventory createMiscellaneousTypeInventory() {
        return new MiscellaneousType.Inventory();
    }

    /**
     * Create an instance of {@link MiscellaneousBase }
     * 
     */
    public MiscellaneousBase createMiscellaneousBase() {
        return new MiscellaneousBase();
    }

    /**
     * Create an instance of {@link MassType }
     * 
     */
    public MassType createMassType() {
        return new MassType();
    }

    /**
     * Create an instance of {@link StyleType }
     * 
     */
    public StyleType createStyleType() {
        return new StyleType();
    }

    /**
     * Create an instance of {@link MiscellaneousAdditionType.Addition }
     * 
     */
    public MiscellaneousAdditionType.Addition createMiscellaneousAdditionTypeAddition() {
        return new MiscellaneousAdditionType.Addition();
    }

    /**
     * Create an instance of {@link DensityRangeType }
     * 
     */
    public DensityRangeType createDensityRangeType() {
        return new DensityRangeType();
    }

    /**
     * Create an instance of {@link BeerXml.Recipes }
     * 
     */
    public BeerXml.Recipes createBeerXmlRecipes() {
        return new BeerXml.Recipes();
    }

    /**
     * Create an instance of {@link MiscellaneousAdditionType }
     * 
     */
    public MiscellaneousAdditionType createMiscellaneousAdditionType() {
        return new MiscellaneousAdditionType();
    }

    /**
     * Create an instance of {@link TemperatureRangeType }
     * 
     */
    public TemperatureRangeType createTemperatureRangeType() {
        return new TemperatureRangeType();
    }

    /**
     * Create an instance of {@link DistanceType }
     * 
     */
    public DistanceType createDistanceType() {
        return new DistanceType();
    }

    /**
     * Create an instance of {@link CultureInformation }
     * 
     */
    public CultureInformation createCultureInformation() {
        return new CultureInformation();
    }

    /**
     * Create an instance of {@link PercentRangeType }
     * 
     */
    public PercentRangeType createPercentRangeType() {
        return new PercentRangeType();
    }

    /**
     * Create an instance of {@link FermentationStageType }
     * 
     */
    public FermentationStageType createFermentationStageType() {
        return new FermentationStageType();
    }

    /**
     * Create an instance of {@link FermentableAdditionType.Addition }
     * 
     */
    public FermentableAdditionType.Addition createFermentableAdditionTypeAddition() {
        return new FermentableAdditionType.Addition();
    }

    /**
     * Create an instance of {@link BeerXml.Procedure }
     * 
     */
    public BeerXml.Procedure createBeerXmlProcedure() {
        return new BeerXml.Procedure();
    }

    /**
     * Create an instance of {@link HopAdditionType }
     * 
     */
    public HopAdditionType createHopAdditionType() {
        return new HopAdditionType();
    }

    /**
     * Create an instance of {@link QuantitativeRangeType }
     * 
     */
    public QuantitativeRangeType createQuantitativeRangeType() {
        return new QuantitativeRangeType();
    }

    /**
     * Create an instance of {@link FermentableAdditionType }
     * 
     */
    public FermentableAdditionType createFermentableAdditionType() {
        return new FermentableAdditionType();
    }

    /**
     * Create an instance of {@link StyleBase }
     * 
     */
    public StyleBase createStyleBase() {
        return new StyleBase();
    }

    /**
     * Create an instance of {@link YeastAdditionType }
     * 
     */
    public YeastAdditionType createYeastAdditionType() {
        return new YeastAdditionType();
    }

    /**
     * Create an instance of {@link FermentableBase }
     * 
     */
    public FermentableBase createFermentableBase() {
        return new FermentableBase();
    }

    /**
     * Create an instance of {@link IBUEstimateType }
     * 
     */
    public IBUEstimateType createIBUEstimateType() {
        return new IBUEstimateType();
    }

    /**
     * Create an instance of {@link RecipeStyleType }
     * 
     */
    public RecipeStyleType createRecipeStyleType() {
        return new RecipeStyleType();
    }

    /**
     * Create an instance of {@link HopVarietyBase }
     * 
     */
    public HopVarietyBase createHopVarietyBase() {
        return new HopVarietyBase();
    }

    /**
     * Create an instance of {@link RecipeType.FermentationStages }
     * 
     */
    public RecipeType.FermentationStages createRecipeTypeFermentationStages() {
        return new RecipeType.FermentationStages();
    }

    /**
     * Create an instance of {@link BeerXml.Styles }
     * 
     */
    public BeerXml.Styles createBeerXmlStyles() {
        return new BeerXml.Styles();
    }

    /**
     * Create an instance of {@link ColorRangeType }
     * 
     */
    public ColorRangeType createColorRangeType() {
        return new ColorRangeType();
    }

    /**
     * Create an instance of {@link RecipeType.Ingredients }
     * 
     */
    public RecipeType.Ingredients createRecipeTypeIngredients() {
        return new RecipeType.Ingredients();
    }

    /**
     * Create an instance of {@link VarietyInformation }
     * 
     */
    public VarietyInformation createVarietyInformation() {
        return new VarietyInformation();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link CultureBase }
     * 
     */
    public CultureBase createCultureBase() {
        return new CultureBase();
    }

    /**
     * Create an instance of {@link WaterType }
     * 
     */
    public WaterType createWaterType() {
        return new WaterType();
    }

    /**
     * Create an instance of {@link BeerXml.MiscellaneousIngredients }
     * 
     */
    public BeerXml.MiscellaneousIngredients createBeerXmlMiscellaneousIngredients() {
        return new BeerXml.MiscellaneousIngredients();
    }

    /**
     * Create an instance of {@link BeerXml.HopVarieties }
     * 
     */
    public BeerXml.HopVarieties createBeerXmlHopVarieties() {
        return new BeerXml.HopVarieties();
    }

    /**
     * Create an instance of {@link WaterAdditionType.Addition }
     * 
     */
    public WaterAdditionType.Addition createWaterAdditionTypeAddition() {
        return new WaterAdditionType.Addition();
    }

    /**
     * Create an instance of {@link CultureInformation.Inventory }
     * 
     */
    public CultureInformation.Inventory createCultureInformationInventory() {
        return new CultureInformation.Inventory();
    }

    /**
     * Create an instance of {@link BeerXml.Profiles }
     * 
     */
    public BeerXml.Profiles createBeerXmlProfiles() {
        return new BeerXml.Profiles();
    }

    /**
     * Create an instance of {@link PressureType }
     * 
     */
    public PressureType createPressureType() {
        return new PressureType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link RecipeType }
     * 
     */
    public RecipeType createRecipeType() {
        return new RecipeType();
    }

    /**
     * Create an instance of {@link DensityType }
     * 
     */
    public DensityType createDensityType() {
        return new DensityType();
    }

    /**
     * Create an instance of {@link WaterAdditionType }
     * 
     */
    public WaterAdditionType createWaterAdditionType() {
        return new WaterAdditionType();
    }

    /**
     * Create an instance of {@link VarietyInformation.Inventory }
     * 
     */
    public VarietyInformation.Inventory createVarietyInformationInventory() {
        return new VarietyInformation.Inventory();
    }

    /**
     * Create an instance of {@link CultureInformation.Inventory.Culture }
     * 
     */
    public CultureInformation.Inventory.Culture createCultureInformationInventoryCulture() {
        return new CultureInformation.Inventory.Culture();
    }

    /**
     * Create an instance of {@link MashProcedureType }
     * 
     */
    public MashProcedureType createMashProcedureType() {
        return new MashProcedureType();
    }

    /**
     * Create an instance of {@link GrainType }
     * 
     */
    public GrainType createGrainType() {
        return new GrainType();
    }

    /**
     * Create an instance of {@link WaterBase }
     * 
     */
    public WaterBase createWaterBase() {
        return new WaterBase();
    }

    /**
     * Create an instance of {@link MashProcedureType.MashSteps }
     * 
     */
    public MashProcedureType.MashSteps createMashProcedureTypeMashSteps() {
        return new MashProcedureType.MashSteps();
    }

    /**
     * Create an instance of {@link RecipeType.Taste }
     * 
     */
    public RecipeType.Taste createRecipeTypeTaste() {
        return new RecipeType.Taste();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link ColorType }
     * 
     */
    public ColorType createColorType() {
        return new ColorType();
    }

    /**
     * Create an instance of {@link MashStepType }
     * 
     */
    public MashStepType createMashStepType() {
        return new MashStepType();
    }

    /**
     * Create an instance of {@link MiscellaneousType }
     * 
     */
    public MiscellaneousType createMiscellaneousType() {
        return new MiscellaneousType();
    }

}
