//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 02:00:16 PM MDT 
//


package jaxb.beerxml2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecipeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * <complexType name="RecipeType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="type">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <enumeration value="extract"/>
 *               <enumeration value="partial mash"/>
 *               <enumeration value="all grain"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="author">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="coauthor" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="created" type="{urn:beerxml:unit:v2}DateType" minOccurs="0"/>
 *         <element name="batch_size" type="{urn:beerxml:unit:v2}VolumeType"/>
 *         <element name="boil_size" type="{urn:beerxml:unit:v2}VolumeType"/>
 *         <element name="boil_time" type="{urn:beerxml:unit:v2}TimeType"/>
 *         <element name="efficiency" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *         <element name="style" type="{urn:beerxml:style:v2}RecipeStyleType" minOccurs="0"/>
 *         <element name="ingredients">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="grain_bill" type="{urn:beerxml:fermentable:v2}FermentableAdditionType"/>
 *                   <element name="hop_bill" type="{urn:beerxml:hop:v2}HopAdditionType" minOccurs="0"/>
 *                   <element name="adjuncts" type="{urn:beerxml:miscellaneous:v2}MiscellaneousAdditionType" minOccurs="0"/>
 *                   <element name="yeast_additions" type="{urn:beerxml:yeast:v2}YeastAdditionType" minOccurs="0"/>
 *                   <element name="water_profile" type="{urn:beerxml:water:v2}WaterAdditionType" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="mash" type="{urn:beerxml:mash:v2}MashProcedureType" minOccurs="0"/>
 *         <element name="notes" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="original_gravity" type="{urn:beerxml:unit:v2}DensityType" minOccurs="0"/>
 *         <element name="final_gravity" type="{urn:beerxml:unit:v2}DensityType" minOccurs="0"/>
 *         <element name="alcohol_by_volume" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *         <element name="ibu_estimate" type="{urn:beerxml:hop:v2}IBUEstimateType" minOccurs="0"/>
 *         <element name="color_estimate" type="{urn:beerxml:unit:v2}ColorType" minOccurs="0"/>
 *         <element name="carbonation" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="fermentation_stages" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="primary" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
 *                   <element name="secondary" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
 *                   <element name="tertiary" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
 *                   <element name="conditioning" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="taste" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="notes">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="rating">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="calories_per_pint" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecipeType", namespace = "urn:beerxml:recipe:v2", propOrder = {
    "name",
    "type",
    "author",
    "coauthor",
    "created",
    "batchSize",
    "boilSize",
    "boilTime",
    "efficiency",
    "style",
    "ingredients",
    "mash",
    "notes",
    "originalGravity",
    "finalGravity",
    "alcoholByVolume",
    "ibuEstimate",
    "colorEstimate",
    "carbonation",
    "fermentationStages",
    "taste",
    "caloriesPerPint"
})
public class RecipeType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String author;
    protected String coauthor;
    protected String created;
    @XmlElement(name = "batch_size", required = true)
    protected VolumeType batchSize;
    @XmlElement(name = "boil_size", required = true)
    protected VolumeType boilSize;
    @XmlElement(name = "boil_time", required = true)
    protected TimeType boilTime;
    protected BigDecimal efficiency;
    protected RecipeStyleType style;
    @XmlElement(required = true)
    protected RecipeType.Ingredients ingredients;
    protected MashProcedureType mash;
    protected String notes;
    @XmlElement(name = "original_gravity")
    protected DensityType originalGravity;
    @XmlElement(name = "final_gravity")
    protected DensityType finalGravity;
    @XmlElement(name = "alcohol_by_volume")
    protected BigDecimal alcoholByVolume;
    @XmlElement(name = "ibu_estimate")
    protected IBUEstimateType ibuEstimate;
    @XmlElement(name = "color_estimate")
    protected ColorType colorEstimate;
    protected BigDecimal carbonation;
    @XmlElement(name = "fermentation_stages")
    protected RecipeType.FermentationStages fermentationStages;
    protected RecipeType.Taste taste;
    @XmlElement(name = "calories_per_pint")
    protected BigDecimal caloriesPerPint;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the coauthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoauthor() {
        return coauthor;
    }

    /**
     * Sets the value of the coauthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoauthor(String value) {
        this.coauthor = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreated(String value) {
        this.created = value;
    }

    /**
     * Gets the value of the batchSize property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeType }
     *     
     */
    public VolumeType getBatchSize() {
        return batchSize;
    }

    /**
     * Sets the value of the batchSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeType }
     *     
     */
    public void setBatchSize(VolumeType value) {
        this.batchSize = value;
    }

    /**
     * Gets the value of the boilSize property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeType }
     *     
     */
    public VolumeType getBoilSize() {
        return boilSize;
    }

    /**
     * Sets the value of the boilSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeType }
     *     
     */
    public void setBoilSize(VolumeType value) {
        this.boilSize = value;
    }

    /**
     * Gets the value of the boilTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeType }
     *     
     */
    public TimeType getBoilTime() {
        return boilTime;
    }

    /**
     * Sets the value of the boilTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeType }
     *     
     */
    public void setBoilTime(TimeType value) {
        this.boilTime = value;
    }

    /**
     * Gets the value of the efficiency property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEfficiency() {
        return efficiency;
    }

    /**
     * Sets the value of the efficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEfficiency(BigDecimal value) {
        this.efficiency = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeStyleType }
     *     
     */
    public RecipeStyleType getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeStyleType }
     *     
     */
    public void setStyle(RecipeStyleType value) {
        this.style = value;
    }

    /**
     * Gets the value of the ingredients property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeType.Ingredients }
     *     
     */
    public RecipeType.Ingredients getIngredients() {
        return ingredients;
    }

    /**
     * Sets the value of the ingredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeType.Ingredients }
     *     
     */
    public void setIngredients(RecipeType.Ingredients value) {
        this.ingredients = value;
    }

    /**
     * Gets the value of the mash property.
     * 
     * @return
     *     possible object is
     *     {@link MashProcedureType }
     *     
     */
    public MashProcedureType getMash() {
        return mash;
    }

    /**
     * Sets the value of the mash property.
     * 
     * @param value
     *     allowed object is
     *     {@link MashProcedureType }
     *     
     */
    public void setMash(MashProcedureType value) {
        this.mash = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the originalGravity property.
     * 
     * @return
     *     possible object is
     *     {@link DensityType }
     *     
     */
    public DensityType getOriginalGravity() {
        return originalGravity;
    }

    /**
     * Sets the value of the originalGravity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityType }
     *     
     */
    public void setOriginalGravity(DensityType value) {
        this.originalGravity = value;
    }

    /**
     * Gets the value of the finalGravity property.
     * 
     * @return
     *     possible object is
     *     {@link DensityType }
     *     
     */
    public DensityType getFinalGravity() {
        return finalGravity;
    }

    /**
     * Sets the value of the finalGravity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityType }
     *     
     */
    public void setFinalGravity(DensityType value) {
        this.finalGravity = value;
    }

    /**
     * Gets the value of the alcoholByVolume property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlcoholByVolume() {
        return alcoholByVolume;
    }

    /**
     * Sets the value of the alcoholByVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlcoholByVolume(BigDecimal value) {
        this.alcoholByVolume = value;
    }

    /**
     * Gets the value of the ibuEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link IBUEstimateType }
     *     
     */
    public IBUEstimateType getIbuEstimate() {
        return ibuEstimate;
    }

    /**
     * Sets the value of the ibuEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IBUEstimateType }
     *     
     */
    public void setIbuEstimate(IBUEstimateType value) {
        this.ibuEstimate = value;
    }

    /**
     * Gets the value of the colorEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link ColorType }
     *     
     */
    public ColorType getColorEstimate() {
        return colorEstimate;
    }

    /**
     * Sets the value of the colorEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorType }
     *     
     */
    public void setColorEstimate(ColorType value) {
        this.colorEstimate = value;
    }

    /**
     * Gets the value of the carbonation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCarbonation() {
        return carbonation;
    }

    /**
     * Sets the value of the carbonation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCarbonation(BigDecimal value) {
        this.carbonation = value;
    }

    /**
     * Gets the value of the fermentationStages property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeType.FermentationStages }
     *     
     */
    public RecipeType.FermentationStages getFermentationStages() {
        return fermentationStages;
    }

    /**
     * Sets the value of the fermentationStages property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeType.FermentationStages }
     *     
     */
    public void setFermentationStages(RecipeType.FermentationStages value) {
        this.fermentationStages = value;
    }

    /**
     * Gets the value of the taste property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeType.Taste }
     *     
     */
    public RecipeType.Taste getTaste() {
        return taste;
    }

    /**
     * Sets the value of the taste property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeType.Taste }
     *     
     */
    public void setTaste(RecipeType.Taste value) {
        this.taste = value;
    }

    /**
     * Gets the value of the caloriesPerPint property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCaloriesPerPint() {
        return caloriesPerPint;
    }

    /**
     * Sets the value of the caloriesPerPint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCaloriesPerPint(BigDecimal value) {
        this.caloriesPerPint = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="primary" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
     *         <element name="secondary" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
     *         <element name="tertiary" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
     *         <element name="conditioning" type="{urn:beerxml:recipe:v2}FermentationStageType" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "primary",
        "secondary",
        "tertiary",
        "conditioning"
    })
    public static class FermentationStages {

        @XmlElement(namespace = "urn:beerxml:recipe:v2")
        protected FermentationStageType primary;
        @XmlElement(namespace = "urn:beerxml:recipe:v2")
        protected FermentationStageType secondary;
        @XmlElement(namespace = "urn:beerxml:recipe:v2")
        protected FermentationStageType tertiary;
        @XmlElement(namespace = "urn:beerxml:recipe:v2")
        protected FermentationStageType conditioning;

        /**
         * Gets the value of the primary property.
         * 
         * @return
         *     possible object is
         *     {@link FermentationStageType }
         *     
         */
        public FermentationStageType getPrimary() {
            return primary;
        }

        /**
         * Sets the value of the primary property.
         * 
         * @param value
         *     allowed object is
         *     {@link FermentationStageType }
         *     
         */
        public void setPrimary(FermentationStageType value) {
            this.primary = value;
        }

        /**
         * Gets the value of the secondary property.
         * 
         * @return
         *     possible object is
         *     {@link FermentationStageType }
         *     
         */
        public FermentationStageType getSecondary() {
            return secondary;
        }

        /**
         * Sets the value of the secondary property.
         * 
         * @param value
         *     allowed object is
         *     {@link FermentationStageType }
         *     
         */
        public void setSecondary(FermentationStageType value) {
            this.secondary = value;
        }

        /**
         * Gets the value of the tertiary property.
         * 
         * @return
         *     possible object is
         *     {@link FermentationStageType }
         *     
         */
        public FermentationStageType getTertiary() {
            return tertiary;
        }

        /**
         * Sets the value of the tertiary property.
         * 
         * @param value
         *     allowed object is
         *     {@link FermentationStageType }
         *     
         */
        public void setTertiary(FermentationStageType value) {
            this.tertiary = value;
        }

        /**
         * Gets the value of the conditioning property.
         * 
         * @return
         *     possible object is
         *     {@link FermentationStageType }
         *     
         */
        public FermentationStageType getConditioning() {
            return conditioning;
        }

        /**
         * Sets the value of the conditioning property.
         * 
         * @param value
         *     allowed object is
         *     {@link FermentationStageType }
         *     
         */
        public void setConditioning(FermentationStageType value) {
            this.conditioning = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="grain_bill" type="{urn:beerxml:fermentable:v2}FermentableAdditionType"/>
     *         <element name="hop_bill" type="{urn:beerxml:hop:v2}HopAdditionType" minOccurs="0"/>
     *         <element name="adjuncts" type="{urn:beerxml:miscellaneous:v2}MiscellaneousAdditionType" minOccurs="0"/>
     *         <element name="yeast_additions" type="{urn:beerxml:yeast:v2}YeastAdditionType" minOccurs="0"/>
     *         <element name="water_profile" type="{urn:beerxml:water:v2}WaterAdditionType" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "grainBill",
        "hopBill",
        "adjuncts",
        "yeastAdditions",
        "waterProfile"
    })
    public static class Ingredients {

        @XmlElement(name = "grain_bill", namespace = "urn:beerxml:recipe:v2", required = true)
        protected FermentableAdditionType grainBill;
        @XmlElement(name = "hop_bill", namespace = "urn:beerxml:recipe:v2")
        protected HopAdditionType hopBill;
        @XmlElement(namespace = "urn:beerxml:recipe:v2")
        protected MiscellaneousAdditionType adjuncts;
        @XmlElement(name = "yeast_additions", namespace = "urn:beerxml:recipe:v2")
        protected YeastAdditionType yeastAdditions;
        @XmlElement(name = "water_profile", namespace = "urn:beerxml:recipe:v2")
        protected WaterAdditionType waterProfile;

        /**
         * Gets the value of the grainBill property.
         * 
         * @return
         *     possible object is
         *     {@link FermentableAdditionType }
         *     
         */
        public FermentableAdditionType getGrainBill() {
            return grainBill;
        }

        /**
         * Sets the value of the grainBill property.
         * 
         * @param value
         *     allowed object is
         *     {@link FermentableAdditionType }
         *     
         */
        public void setGrainBill(FermentableAdditionType value) {
            this.grainBill = value;
        }

        /**
         * Gets the value of the hopBill property.
         * 
         * @return
         *     possible object is
         *     {@link HopAdditionType }
         *     
         */
        public HopAdditionType getHopBill() {
            return hopBill;
        }

        /**
         * Sets the value of the hopBill property.
         * 
         * @param value
         *     allowed object is
         *     {@link HopAdditionType }
         *     
         */
        public void setHopBill(HopAdditionType value) {
            this.hopBill = value;
        }

        /**
         * Gets the value of the adjuncts property.
         * 
         * @return
         *     possible object is
         *     {@link MiscellaneousAdditionType }
         *     
         */
        public MiscellaneousAdditionType getAdjuncts() {
            return adjuncts;
        }

        /**
         * Sets the value of the adjuncts property.
         * 
         * @param value
         *     allowed object is
         *     {@link MiscellaneousAdditionType }
         *     
         */
        public void setAdjuncts(MiscellaneousAdditionType value) {
            this.adjuncts = value;
        }

        /**
         * Gets the value of the yeastAdditions property.
         * 
         * @return
         *     possible object is
         *     {@link YeastAdditionType }
         *     
         */
        public YeastAdditionType getYeastAdditions() {
            return yeastAdditions;
        }

        /**
         * Sets the value of the yeastAdditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link YeastAdditionType }
         *     
         */
        public void setYeastAdditions(YeastAdditionType value) {
            this.yeastAdditions = value;
        }

        /**
         * Gets the value of the waterProfile property.
         * 
         * @return
         *     possible object is
         *     {@link WaterAdditionType }
         *     
         */
        public WaterAdditionType getWaterProfile() {
            return waterProfile;
        }

        /**
         * Sets the value of the waterProfile property.
         * 
         * @param value
         *     allowed object is
         *     {@link WaterAdditionType }
         *     
         */
        public void setWaterProfile(WaterAdditionType value) {
            this.waterProfile = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="notes">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="rating">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "notes",
        "rating"
    })
    public static class Taste {

        @XmlElement(namespace = "urn:beerxml:recipe:v2", required = true)
        protected String notes;
        @XmlElement(namespace = "urn:beerxml:recipe:v2", required = true)
        protected BigDecimal rating;

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

        /**
         * Gets the value of the rating property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRating() {
            return rating;
        }

        /**
         * Sets the value of the rating property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRating(BigDecimal value) {
            this.rating = value;
        }

    }

}
