//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 02:00:16 PM MDT 
//


package jaxb.beerxml2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Addition of yeast to recipe
 * 
 * <p>Java class for YeastAdditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * <complexType name="YeastAdditionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="addition" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{urn:beerxml:yeast:v2}CultureBase">
 *                 <sequence>
 *                   <choice>
 *                     <element name="amount" type="{urn:beerxml:unit:v2}VolumeType"/>
 *                     <element name="amount_as_weight" type="{urn:beerxml:unit:v2}MassType"/>
 *                   </choice>
 *                   <element name="times_cultured" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="add_to_secondary" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "YeastAdditionType", namespace = "urn:beerxml:yeast:v2", propOrder = {
    "addition"
})
public class YeastAdditionType {

    @XmlElement(required = true)
    protected List<YeastAdditionType.Addition> addition;

    /**
     * Gets the value of the addition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link YeastAdditionType.Addition }
     * 
     * 
     */
    public List<YeastAdditionType.Addition> getAddition() {
        if (addition == null) {
            addition = new ArrayList<YeastAdditionType.Addition>();
        }
        return this.addition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * <complexType>
     *   <complexContent>
     *     <extension base="{urn:beerxml:yeast:v2}CultureBase">
     *       <sequence>
     *         <choice>
     *           <element name="amount" type="{urn:beerxml:unit:v2}VolumeType"/>
     *           <element name="amount_as_weight" type="{urn:beerxml:unit:v2}MassType"/>
     *         </choice>
     *         <element name="times_cultured" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="add_to_secondary" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amount",
        "amountAsWeight",
        "timesCultured",
        "addToSecondary"
    })
    public static class Addition
        extends CultureBase
    {

        @XmlElement(namespace = "urn:beerxml:yeast:v2")
        protected VolumeType amount;
        @XmlElement(name = "amount_as_weight", namespace = "urn:beerxml:yeast:v2")
        protected MassType amountAsWeight;
        @XmlElement(name = "times_cultured", namespace = "urn:beerxml:yeast:v2")
        protected BigInteger timesCultured;
        @XmlElement(name = "add_to_secondary", namespace = "urn:beerxml:yeast:v2")
        protected Boolean addToSecondary;

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link VolumeType }
         *     
         */
        public VolumeType getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link VolumeType }
         *     
         */
        public void setAmount(VolumeType value) {
            this.amount = value;
        }

        /**
         * Gets the value of the amountAsWeight property.
         * 
         * @return
         *     possible object is
         *     {@link MassType }
         *     
         */
        public MassType getAmountAsWeight() {
            return amountAsWeight;
        }

        /**
         * Sets the value of the amountAsWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link MassType }
         *     
         */
        public void setAmountAsWeight(MassType value) {
            this.amountAsWeight = value;
        }

        /**
         * Gets the value of the timesCultured property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTimesCultured() {
            return timesCultured;
        }

        /**
         * Sets the value of the timesCultured property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTimesCultured(BigInteger value) {
            this.timesCultured = value;
        }

        /**
         * Gets the value of the addToSecondary property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAddToSecondary() {
            return addToSecondary;
        }

        /**
         * Sets the value of the addToSecondary property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAddToSecondary(Boolean value) {
            this.addToSecondary = value;
        }

    }

}
